services: 
  model-service: 
    image: ${MODEL_IMAGE}
    environment:
      - PORT=${MODEL_PORT}
    #volumes: 
    #  - ./models:/app/models 
    restart: unless-stopped
  
  app: 
    image: ${APP_IMAGE}
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on: 
      - model-service   
    environment: 
      - PORT=${APP_PORT}
      - MODEL_HOST=http://model-service:${MODEL_PORT}
    restart: unless-stopped
