apiVersion: v1
kind: Service
metadata:
  name: {{ include "sms-checker.fullname" . }}-app
  labels:
    app.kubernetes.io/name: {{ include "sms-checker.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: "app"
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "sms-checker.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: "app"
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
