apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sms-checker.fullname" . }}-app-config
  labels:
    app.kubernetes.io/name: {{ include "sms-checker.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: "app"
data:
  APP_WELCOME_MESSAGE: "Welcome to SMS Checker"
  APP_FEATURE_FLAG_EXAMPLE: "false"
