{{- $defaultModelSvcName := printf "%s-model" (include "sms-checker.fullname" .) }}
{{- $modelServiceName := default $defaultModelSvcName .Values.modelService.serviceNameOverride }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sms-checker.fullname" . }}-app-v1
  labels:
    app.kubernetes.io/name: {{ include "sms-checker.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: "app"
    version: v1
spec:
  replicas: {{ .Values.app.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "sms-checker.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: "app"
      version: v1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "sms-checker.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: "app"
        version: v1
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- range .Values.imagePullSecrets }}
        - name: {{ .name }}
        {{- end }}
      {{- end }}
      containers:
        - name: app
          # STABLE image tag
          image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tagStable }}"
          imagePullPolicy: Always
          env:
            - name: MODEL_SERVICE_URL
              value: "http://{{ $modelServiceName }}:{{ .Values.modelService.servicePort }}"
            - name: MODEL_HOST
              value: "http://{{ $modelServiceName }}:{{ .Values.modelService.servicePort }}"
            # Helpful for debugging / seeing which version answers
            - name: APP_VERSION
              value: "v1"
            - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
              value: "health,info"
            - name: MANAGEMENT_ENDPOINT_PROMETHEUS_ENABLED
              value: "false"

          envFrom:
            - configMapRef:
                name: {{ include "sms-checker.fullname" . }}-app-config
            - secretRef:
                name: {{ include "sms-checker.fullname" . }}-app-secret
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: shared-folder
              mountPath: /mnt/shared
              readOnly: false
      volumes:
        - name: shared-folder
          hostPath:
            path: /mnt/shared
            type: DirectoryOrCreate

