apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sms-checker.fullname" . }}-app-secret
  labels:
    app.kubernetes.io/name: {{ include "sms-checker.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: "app"
type: Opaque
stringData:
  DUMMY_API_KEY: "replace-me-in-real-deployments"
  DUMMY_PASSWORD: "not-used"
