apiVersion: v2
name: sms-checker
description: Helm chart for deploying the SMS Checker application stack
type: application
version: 0.1.0        # The version of the chart
appVersion: "1.0.0"   # Version of the application this chart deploys.